site_name: Cardano Developer Japan
copyright: Copyright &copy; 2024 Cardano Developer Japan

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: light green
      toggle:
        icon: material/weather-night
        name: ダークモード

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: light green
      toggle:
        icon: material/brightness-7
        name: ライトモード

  font:
    text: Noto Sans Japanese
    code: Source Code Pro

  language: ja

  features:
    - content.tabs.link
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage 

  generator: false


plugins:
  - search:
      lang: ja
  - privacy:
      links_attr_map:
        target: _blank


markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - meta
  - codehilite
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
  - 

nav: 
  - 'HOME': 'index.md'
  - 'カルダノとは？': 'what-cardano.md'
  - 'カルダノ開発入門':
    - 'ネットワーク概要' : 'node/cardano-network.md'
    - 'ノードインストール' : 'node/node-install.md'
    - 'ノード起動' : 'node/node-run.md'


